name: "YOLOv4"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 512, 512]
    reshape { shape: [ 1, 3, 512, 512 ] }
  }
]
output [
  {
    name: "confs"
    data_type: TYPE_FP32
    dims: [1, 16128, 80]
  },
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [1, 16128, 1, 4]
  }
]
cc_model_filenames: {}
metric_tags: {}
parameters: {}
model_warmup: []
