name: "Pointpillar_Python"
backend: "python"

input [
  {
    name: "voxels"
    data_type: TYPE_FP32
    dims: [-1, 20, 5]
  }
]
input [
  {
    name: "coordinates"
    data_type: TYPE_INT32
    dims: [-1, 4]
  }
]
input [
  {
    name: "num_points"
    data_type: TYPE_INT32
    dims: [-1]
  }
]
output [
  {
    name: "box3d_lidar"
    data_type: TYPE_FP32
    dims: [-1, 9]
  }
]
output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [-1]
  }
]
output [
  {
    name: "label_preds"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

instance_group [{ kind: KIND_GPU }]
